<?php
return [
    'empty' => [
        'title' => '空',
        'status' => '1',
        'data' => [],
    ],
    'status' => [
        'title' => '状态',
        'status' => '1',
        'data' => [
            '1' => '在用',
            '0' => '停用',
        ],
    ],
    'sex' => [
        'title' => '性别',
        'status' => '1',
        'data' => [
            '1' => '男',
            '0' => '女',
        ],
    ],
    'auth_level' => [
        'title' => '节点类型',
        'status' => '1',
        'data' => [
            '1' => '项目',
            '2' => '模块',
            '3' => '操作',
        ],
    ],
    'whether' => [
        'title' => '是否',
        'status' => '1',
        'data' => [
            '1' => '是',
            '0' => '否',
        ],
    ],
    'switch' => [
        'title' => '是否',
        'status' => '1',
        'data' => [
            '1' => '开',
            '0' => '关',
        ],
    ],
    'texttype' => [
        'title' => '文本类型',
        'status' => '1',
        'data' => [
            'Input' => 'Input [输入框]',
            'Radio' => 'Radio [单选按钮]',
            'Checkbox' => 'Checkbox [复选框]',
            'Select' => 'Select [下拉框]',
            'Selects' => 'Selects [下拉框(多选)]',
            'Textarea' => 'Textarea [多行文本]',
            'Image' => 'Image [单图]',
            'Images' => 'Images [图组]',
            'File' => 'File [单文件]',
            'KindEditor' => 'KindEditor [KindEditor编辑器]',
            'FroalaEditor' => 'FroalaEditor [FroalaEditor编辑器]',
            'Tags' => 'Tags [标签]',
            'DateTime' => 'DateTime [日期和时间]',
            'Switchs' => 'Switchs [开关]',
            'Hidden' => 'Hidden [隐藏表单]',
        ],
    ],
    'texttype_field' => [
        'title' => '文本类型字段',
        'status' => '1',
        'data' => [
            'Input' => [
                'html' => 'Input [输入框]',
                'sets' => 'varchar(250) NULL',
                'is_search' => '1',
                'is_textvalue' => '0',
            ],
            'Radio' => [
                'html' => 'Radio [单选按钮]',
                'sets' => 'varchar(100) NULL',
                'is_search' => '1',
                'is_textvalue' => '1',
            ],
            'Checkbox' => [
                'html' => 'Checkbox [复选框]',
                'sets' => 'varchar(250) NULL',
                'is_search' => '1',
                'is_textvalue' => '1',
            ],
            'Select' => [
                'html' => 'Select [下拉框]',
                'sets' => 'varchar(100) NULL',
                'is_search' => '1',
                'is_textvalue' => '1',
            ],
            'Selects' => [
                'html' => 'Selects [下拉框(多选)]',
                'sets' => 'varchar(250) NULL',
                'is_search' => '1',
                'is_textvalue' => '1',
            ],
            'Textarea' => [
                'html' => 'Textarea [多行文本]',
                'sets' => 'text NULL',
                'is_search' => '0',
                'is_textvalue' => '0',
            ],
            'Image' => [
                'html' => 'Image [单图]',
                'sets' => 'varchar(250) NULL',
                'is_search' => '0',
                'is_textvalue' => '0',
            ],
            'Images' => [
                'html' => 'Images [图组]',
                'sets' => 'text NULL',
                'is_search' => '0',
                'is_textvalue' => '0',
            ],
            'File' => [
                'html' => 'File [单文件]',
                'sets' => 'varchar(250) NULL',
                'is_search' => '0',
                'is_textvalue' => '0',
            ],
            'KindEditor' => [
                'html' => 'KindEditor [KindEditor编辑器]',
                'sets' => 'text NULL',
                'is_search' => '0',
                'is_textvalue' => '0',
            ],
            'FroalaEditor' => [
                'html' => 'FroalaEditor [FroalaEditor编辑器]',
                'sets' => 'text NULL',
                'is_search' => '0',
                'is_textvalue' => '0',
            ],
            'Tags' => [
                'html' => 'Tags [标签]',
                'sets' => 'varchar(250) NULL',
                'is_search' => '0',
                'is_textvalue' => '1',
            ],
            'DateTime' => [
                'html' => 'DateTime [日期和时间]',
                'sets' => 'int(10) UNSIGNED NULL',
                'is_search' => '1',
                'is_textvalue' => '0',
            ],
            'Switchs' => [
                'html' => 'Switchs [开关]',
                'sets' => 'tinyint(1) NULL',
                'is_search' => '1',
                'is_textvalue' => '0',
            ],
            'Hidden' => [
                'html' => 'Hidden [隐藏表单]',
                'sets' => 'varchar(250) NULL',
                'is_search' => '0',
                'is_textvalue' => '0',
            ],
        ],
    ],
    'textvalue' => [
        'title' => '文本选项值',
        'status' => '1',
        'data' => [
            'selectlist_select,empty,false' => '空',
            'selectlist_select,whether,true' => '是否',
            'selectlist_select,sex,true' => '性别',
            'selectlist_select,status,true' => '状态',
            'selectlist_select,switch,true' => '开关',
        ],
    ],
    'validate_rule' => [
        'title' => '验证规则',
        'status' => '1',
        'data' => [
            'require' => '必填',
            'number' => '纯数字 [不包含负数和小数点]',
            'integer' => '整数',
            'float' => '浮点数字',
            'email' => 'email地址',
            'alpha' => '纯字母',
            'alphaNum' => '字母和数字',
            'alphaDash' => '字母和数字，下划线_及破折号-',
            'chs' => '汉字',
            'chsAlpha' => '汉字、字母',
            'chsAlphaNum' => '汉字、字母和数字',
            'chsDash' => '汉字、字母、数字和下划线_及破折号-',
            'lower' => '小写字符',
            'upper' => '大写字符',
            'activeUrl' => '域名或者IP',
            'url' => 'URL地址',
            'ip' => 'IP地址',
            'mobile' => '手机号码',
            'idCard' => '身份证格式',
            'zip' => '邮政编码',
        ],
    ],
    'print_position' => [
        'title' => '水印位置',
        'status' => '1',
        'data' => [
            '1' => '左上角',
            '2' => '上居中',
            '3' => '右上角',
            '4' => '左居中',
            '5' => '居中',
            '6' => '右居中',
            '7' => '左下角',
            '8' => '下居中',
            '9' => '右下角',
        ],
    ],
    'target' => [
        'title' => '弹出方式',
        'status' => '1',
        'data' => [
            '_self' => '当前页',
            '_blank' => '新页面',
        ],
    ],
    'flag' => [
        'title' => '属性',
        'status' => '1',
        'data' => [
            'h' => '头条',
            'a' => '特荐',
            'c' => '推荐',
            's' => '滚动',
            'p' => '图片',
            'j' => '跳转',
        ],
    ],
    'list_rows' => [
        'title' => '每页数量',
        'status' => '1',
        'data' => [
            '10' => '10',
            '15' => '15',
            '20' => '20',
            '50' => '50',
            '100' => '100',
            '500' => '500',
        ],
    ],
    'lang' => [
        'title' => '多语言',
        'status' => '1',
        'data' => [
            '' => '请选择',
            'zh-cn' => '中文',
            'en' => '英语',
            'ja' => '日语',
            'ko' => '韩语',
            'fr' => '法语',
            'es' => '西班牙语',
            'pt' => '葡萄牙语',
            'it' => '意大利语',
            'ru' => '俄语',
            'vi' => '越南语',
            'de' => '德语',
            'ar' => '阿拉伯语',
            'id' => '印度尼西亚语',
            'el' => '希腊语',
            'nl' => '荷兰语',
            'pl' => '波兰语',
            'bg' => '保加利亚语',
            'et' => '爱沙尼亚语',
            'da' => '丹麦语',
            'fi' => '芬兰语',
            'cs' => '捷克语',
            'ro' => '罗马尼亚语',
            'sl' => '斯洛文尼亚语',
            'sv' => '瑞典语',
            'hu' => '匈牙利语',
            'tr' => '土耳其语',
            'uk' => '乌克兰语',
            'ms' => '马来语',
            'no' => '挪威语',
            'ne' => '尼泊尔语',
            'hi' => '印地语',
            'sk' => '斯洛伐克语',
            'ga' => '爱尔兰语',
            'kk' => '哈萨克语',
            'lo' => '老挝语',
            'mn' => '蒙古语',
            'my' => '缅甸语',
            'th' => '泰语',
        ],
    ],
    'lang_icon' => [
        'title' => '多语言图标',
        'status' => '1',
        'data' => [
            'zh-cn' => '/static/system/lang/zh-cn.png',
            'en' => '/static/system/lang/en.png',
            'ja' => '/static/system/lang/ja.png',
            'ko' => '/static/system/lang/ko.png',
            'fr' => '/static/system/lang/fr.png',
            'es' => '/static/system/lang/es.png',
            'pt' => '/static/system/lang/pt.png',
            'it' => '/static/system/lang/it.png',
            'ru' => '/static/system/lang/ru.png',
            'vi' => '/static/system/lang/vi.png',
            'de' => '/static/system/lang/de.png',
            'ar' => '/static/system/lang/ar.png',
            'id' => '/static/system/lang/id.png',
            'el' => '/static/system/lang/el.png',
            'nl' => '/static/system/lang/nl.png',
            'pl' => '/static/system/lang/pl.png',
            'bg' => '/static/system/lang/bg.png',
            'et' => '/static/system/lang/et.png',
            'da' => '/static/system/lang/da.png',
            'fi' => '/static/system/lang/fi.png',
            'cs' => '/static/system/lang/cs.png',
            'ro' => '/static/system/lang/ro.png',
            'sl' => '/static/system/lang/sl.png',
            'sv' => '/static/system/lang/sv.png',
            'hu' => '/static/system/lang/hu.png',
            'tr' => '/static/system/lang/tr.png',
            'uk' => '/static/system/lang/uk.png',
            'ms' => '/static/system/lang/ms.png',
            'no' => '/static/system/lang/no.png',
            'ne' => '/static/system/lang/ne.png',
            'hi' => '/static/system/lang/hi.png',
            'sk' => '/static/system/lang/sk.png',
            'ga' => '/static/system/lang/ga.png',
            'kk' => '/static/system/lang/kk.png',
            'lo' => '/static/system/lang/lo.png',
            'mn' => '/static/system/lang/mn.png',
            'my' => '/static/system/lang/my.png',
            'th' => '/static/system/lang/th.png',
        ],
    ],
];