<?php
return [
    'status' => [
        'title' => '状态',
        'status' => '1',
        'data' => [
            '1' => '在用',
            '0' => '停用',
        ],
    ],
    'sex' => [
        'title' => '性别',
        'status' => '1',
        'data' => [
            '1' => '男',
            '0' => '女',
        ],
    ],
    'auth_level' => [
        'title' => '节点类型',
        'status' => '1',
        'data' => [
            '1' => '项目',
            '2' => '模块',
            '3' => '操作',
        ],
    ],
    'whether' => [
        'title' => '是否',
        'status' => '1',
        'data' => [
            '1' => '是',
            '0' => '否',
        ],
    ],
    'texttype' => [
        'title' => '文本类型',
        'status' => '1',
        'data' => [
            'Input' => 'Input',
            'Select' => 'Select',
            'Textarea' => 'Textarea',
            'Content' => 'Content',
            'Checkbox' => 'Checkbox',
            'Radio' => 'Radio',
            'FileUpload' => 'FileUpload',
        ],
    ],
    'print_position' => [
        'title' => '水印位置',
        'status' => '1',
        'data' => [
            '1' => '左上角',
            '2' => '上居中',
            '3' => '右上角',
            '4' => '左居中',
            '5' => '居中',
            '6' => '右居中',
            '7' => '左下角',
            '8' => '下居中',
            '9' => '右下角',
        ],
    ],
    'arctype_mod' => [
        'title' => '分类模型',
        'status' => '1',
        'data' => [
            'archive' => '文章模型',
            // 'mood' => '动态模型',
            // 'goods' => '商品模型',
            'page' => '单页',
            'jump' => '外部链接',
        ],
    ],
    'target' => [
        'title' => '弹出方式',
        'status' => '1',
        'data' => [
            '_self' => '当前页',
            '_blank' => '新页面',
        ],
    ],
    'flag' => [
        'title' => '属性',
        'status' => '1',
        'data' => [
            'h' => '头条',
            'a' => '特荐',
            'c' => '推荐',
            's' => '滚动',
            'p' => '图片',
            'j' => '跳转',
        ],
    ],
    'list_rows' => [
        'title' => '每页数量',
        'status' => '1',
        'data' => [
            '10' => '10',
            '15' => '15',
            '20' => '20',
            '50' => '50',
            '100' => '100',
            '500' => '500',
        ],
    ],
    'lang' => [
        'title' => '多语言',
        'status' => '1',
        'data' => [
            '' => '请选择',
            'zh-cn' => '中文',
            'en' => '英语',
            'ja' => '日语',
            'ko' => '韩语',
            'fr' => '法语',
            'es' => '西班牙语',
            'pt' => '葡萄牙语',
            'it' => '意大利语',
            'ru' => '俄语',
            'vi' => '越南语',
            'de' => '德语',
            'ar' => '阿拉伯语',
            'id' => '印度尼西亚语',
            'el' => '希腊语',
            'nl' => '荷兰语',
            'pl' => '波兰语',
            'bg' => '保加利亚语',
            'et' => '爱沙尼亚语',
            'da' => '丹麦语',
            'fi' => '芬兰语',
            'cs' => '捷克语',
            'ro' => '罗马尼亚语',
            'sl' => '斯洛文尼亚语',
            'sv' => '瑞典语',
            'hu' => '匈牙利语',
            'tr' => '土耳其语',
            'uk' => '乌克兰语',
            'ms' => '马来语',
            'no' => '挪威语',
            'ne' => '尼泊尔语',
            'hi' => '印地语',
            'sk' => '斯洛伐克语',
            'ga' => '爱尔兰语',
            'kk' => '哈萨克语',
            'lo' => '老挝语',
            'mn' => '蒙古语',
            'my' => '缅甸语',
            'th' => '泰语',
        ],
    ],
    'lang_icon' => [
        'title' => '多语言图标',
        'status' => '1',
        'data' => [
            'zh-cn' => '/static/lang/zh-cn.png',
            'en' => '/static/lang/en.png',
            'ja' => '/static/lang/ja.png',
            'ko' => '/static/lang/ko.png',
            'fr' => '/static/lang/fr.png',
            'es' => '/static/lang/es.png',
            'pt' => '/static/lang/pt.png',
            'it' => '/static/lang/it.png',
            'ru' => '/static/lang/ru.png',
            'vi' => '/static/lang/vi.png',
            'de' => '/static/lang/de.png',
            'ar' => '/static/lang/ar.png',
            'id' => '/static/lang/id.png',
            'el' => '/static/lang/el.png',
            'nl' => '/static/lang/nl.png',
            'pl' => '/static/lang/pl.png',
            'bg' => '/static/lang/bg.png',
            'et' => '/static/lang/et.png',
            'da' => '/static/lang/da.png',
            'fi' => '/static/lang/fi.png',
            'cs' => '/static/lang/cs.png',
            'ro' => '/static/lang/ro.png',
            'sl' => '/static/lang/sl.png',
            'sv' => '/static/lang/sv.png',
            'hu' => '/static/lang/hu.png',
            'tr' => '/static/lang/tr.png',
            'uk' => '/static/lang/uk.png',
            'ms' => '/static/lang/ms.png',
            'no' => '/static/lang/no.png',
            'ne' => '/static/lang/ne.png',
            'hi' => '/static/lang/hi.png',
            'sk' => '/static/lang/sk.png',
            'ga' => '/static/lang/ga.png',
            'kk' => '/static/lang/kk.png',
            'lo' => '/static/lang/lo.png',
            'mn' => '/static/lang/mn.png',
            'my' => '/static/lang/my.png',
            'th' => '/static/lang/th.png',
        ],
    ],
];